kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: s3
  namespace: default
spec:
  selector:
    matchLabels:
      app: s3
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "default"
        app: s3
    spec:
      serviceAccountName: s3
      containers:
        - name: driver
          image: "image/tag:v1.2.0"
          imagePullPolicy: Always
          args:
            - --some-arg=$(some-var)/more/stuff
        - name: csi-s3
          image: "iamge/tag:archive-amd64"
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: $(some-var)/pods
              mountPropagation: Bidirectional
              name: mountpoint-dir
      volumes:
        - hostPath:
            path: $(some-var)/plugins
            type: DirectoryOrCreate
          name: socket-dir
