apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: dlf
namespace: dlf
resources:
  - daemonset.yaml
configMapGenerator:
- name: params
  envs:
  - params.env
generatorOptions:
  disableNameSuffixHash: true
vars:
- name: some-var
  objref:
    kind: ConfigMap
    name: params
    apiVersion: v1
  fieldref:
    fieldpath: data.some-var
